version: "3.8"
services:
  database:
    container_name: pg-db
    image: postgres:13.0
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=unicorn_user
      - POSTGRES_PASSWORD=magical_password
      - POSTGRES_DB=rainbow_database
    volumes:
      - database-data:/var/lib/postgresql/data/

volumes:
  database-data:

